apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: kuzuk
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-service:9090
      isDefault: true
      editable: true
    - name: Kuzuk-Logs
      type: loki
      access: proxy
      url: http://loki:3100
      editable: true
    - name: Kuzuk-Metrics
      type: prometheus
      access: proxy
      url: http://prometheus-service:9090
      jsonData:
        timeInterval: "5s"
        queryTimeout: "60s"
      editable: true