apiVersion: v1
kind: PersistentVolume
metadata:
  name: kuzuk-pv
  labels:
    app: kuzuk
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kuzuk-storage
  hostPath:
    path: /mnt/kuzuk-data
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuzuk-pvc
  namespace: kuzuk
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: kuzuk-storage

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kuzuk-storage
provisioner: kubernetes.io/host-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain